# Generated by Django 5.1.15 on 2026-04-24 10:54

import apps.catalogue.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0003_alter_community_invite_code'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('requires_fssai', models.BooleanField(default=False)),
                ('requires_gstin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('max_daily_qty', models.PositiveIntegerField()),
                ('available_from', models.TimeField()),
                ('available_to', models.TimeField()),
                ('delivery_days', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_subscription', models.BooleanField(default=False)),
                ('is_flash_sale', models.BooleanField(default=False)),
                ('flash_sale_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('flash_sale_qty_remaining', models.PositiveIntegerField(blank=True, null=True)),
                ('flash_sale_ends_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalogue.category')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='communities.community')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='vendors.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='DailyInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('qty_ordered', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_inventory', to='catalogue.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(storage=apps.catalogue.storage.ProductMediaStorage(), upload_to=apps.catalogue.storage.product_image_upload_path)),
                ('thumbnail_s3_key', models.CharField(blank=True, max_length=500)),
                ('thumbnail_s3_key_small', models.CharField(blank=True, max_length=500)),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalogue.product')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['community', 'is_active'], name='catalogue_p_communi_6a14c0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['community', 'category', 'is_active'], name='catalogue_p_communi_785631_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['vendor', 'is_active'], name='catalogue_p_vendor__75d0ab_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyinventory',
            constraint=models.UniqueConstraint(fields=('product', 'date'), name='unique_product_date_inventory'),
        ),
    ]
