# Generated by Django 5.1.15 on 2026-04-21 16:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0003_alter_community_invite_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=150)),
                ('bio', models.TextField(blank=True)),
                ('logistics_tier', models.CharField(choices=[('tier_a', 'Self-delivery, own bike/van'), ('tier_b', 'NammaNeighbor pickup required')], max_length=6)),
                ('is_food_seller', models.BooleanField(default=False)),
                ('govt_id_s3_key', models.CharField(blank=True, max_length=500)),
                ('bank_proof_s3_key', models.CharField(blank=True, max_length=500)),
                ('fssai_number', models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'FSSAI number must be exactly 14 digits.')])),
                ('fssai_status', models.CharField(choices=[('not_applicable', 'Not Applicable'), ('pending', 'Pending'), ('verified', 'Verified'), ('expired', 'Expired'), ('failed', 'Failed')], default='not_applicable', max_length=14)),
                ('fssai_cert_s3_key', models.CharField(blank=True, max_length=500)),
                ('fssai_verified_at', models.DateTimeField(blank=True, null=True)),
                ('fssai_expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('fssai_business_name', models.CharField(blank=True, max_length=200)),
                ('fssai_authorized_categories', models.JSONField(default=list)),
                ('fssai_expiry_warning_sent', models.BooleanField(default=False)),
                ('gstin', models.CharField(blank=True, max_length=15)),
                ('gst_cert_s3_key', models.CharField(blank=True, max_length=500)),
                ('razorpay_account_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_account_status', models.CharField(blank=True, max_length=20)),
                ('razorpay_onboarding_step', models.CharField(blank=True, max_length=50)),
                ('bank_account_verified', models.BooleanField(default=False)),
                ('completed_delivery_count', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VendorCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], max_length=14)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('delist_threshold', models.PositiveIntegerField(default=2)),
                ('missed_window_count', models.PositiveIntegerField(default=0)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_approvals', to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_memberships', to='communities.community')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_memberships', to='vendors.vendor')),
            ],
            options={
                'indexes': [models.Index(fields=['community', 'status'], name='vendors_ven_communi_9b88e8_idx')],
                'constraints': [models.UniqueConstraint(fields=('vendor', 'community'), name='unique_vendor_community')],
            },
        ),
    ]
