# Generated by Django 5.1.15 on 2026-04-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_community_full_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='invite_code',
            field=models.CharField(blank=True, db_index=True, max_length=6, unique=True),
        ),
    ]
